### PR TITLE
feat(customUrl) add support for custom Resource Hacker download

### PR DESCRIPTION
**Pull request by elliott-pd**

### CODE REVIEW

**Comment by evshiron** [comment]
Greetings. This PR looks good to me, but I suggest using an environment variable, so that `nwjs-builder` can be left unchanged, as well as any potential dependents (don't like passing arguments around).
Also I want `customUrl` to be `source`, with a few lines of code we can support local Resource Hacker archive as well.
Any ideas?

**Comment by elliott-pd** [comment]
Greetings, 

I don't have an issue with using an environment variable instead, I think that is a reasonable solution that avoid having to update nwjs-builder as well. Having to update dependents just for a new optional param isn't really ideal.

Being able to specify an local source for Resource Hacker sounds like a great idea. 

Any problems with having two environment variables then, one for local resource and one for a source url?

**Comment by evshiron** [comment]
> Any problems with having two environment variables then, one for local resource and one for a source url?

Why don't we use a single `SOURCE_RESOURCE_HACKER` and check if it starts with "http" or "https"?

**Comment by elliott-pd** [comment]
> Why don't we use a single SOURCE_RESOURCE_HACKER and check if it starts with "http" or "https"?

I think that's reasonable. I'll whip something up.

EDIT:
We could actually just check if it starts with http and that'll cover both cases.

I think if we change make it so it checks the env variable, if it doesn't exist it will substitute the base download URL. After failing to find the local file, it can check for "http" and download the file else immediately try to extract the file.

I think it should throw an exception if it fails to find the file when attempting to extract from the specified local path, thoughts?

**Comment by evshiron** [comment]
`node-resourcehacker` 1.2.1 has been released and should now have the changes on. Congrats!

**Pull request closed without merging**
